# # Template vir waneer nuwe customer signup om subdomains te point
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-service
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   # tls nog nie nodig nie, net waneer https gebruiyk word
#   tls:
#     - pigeon.com
#   rules:
#     - host: customer1.pigeon.com
#       http:
#         paths:
#           - path: /api
#             backend:
#               serviceName: core-api-cluster-ip-service
#               servicePort: 5000
#           - path: /
#             backend:
#               serviceName: core-frontend-cluster-ip-service
#               servicePort: 3000
        
